### ISSUE TITLE
保存時に数値フィールドの小数点が削除される

### ISSUE THREAD

**Issue by sada-nishio** [kintone-samples/kintone-spreadsheet#60]
下記が該当部分かと思いますが小数点のピリオドが保存時に削除されてしまうようです。
https://github.com/mura-/kintone-spreadsheet/blob/f46b305ce2b88a307e78bd44a2074d4dd9c627b6/src/js/spreadsheet/hooks.ts#L30

**Comment by mura-** [comment]
@sada-nishio 
おそくなってすいませんが、下記修正版をリリースしました。
https://github.com/mura-/kintone-spreadsheet/releases/tag/v1.0.3

**Comment by sada-nishio** [comment]
@mura- ありがとうございます！修正確認できました。
